### ISSUE TITLE
Fazer barramento de serviços

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/2018.1-Dulce_API#14]
Nessa issue deve ser feito:
Preparar o Sistema para se conectar com o Barramento de Serviços (Rabbitmq).

**Comment by alvesisaque** [comment]
@egewarth  e @gag2502 vocês devem parear para concluir essa atividade!

**Comment by alvesisaque** [comment]
Por não ser possível a conclusão dessa issue, ela foi como débito técnico para a sprint 5
