### ISSUE TITLE
Visualizar hospitais

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/2018.1-Dulce_API#28]
Eu, como **front end** desejo **receber a lista de hospitais** a fim de **mostrar os hospitais a um supervisor**

Critérios de aceitação:
- Gerar uma lista com todos os hospitais;
- exigir token de login;
- verificar se é um supervisor.
- testes

**Comment by alvesisaque** [comment]
@EzequielDeOliveira, @fepas organizem a issue de vocês ainda hoje de acordo com o treinamento passado para vocês

**Comment by gag2502** [comment]
@EzequielDeOliveira @fepas  me procurem caso haja dificuldades :grinning:
