### ISSUE TITLE
Visualizar setores

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/2018.1-Dulce_API#29]
Eu, como **front end** desejo **receber a lista de setores de um hospital** a fim de **mostrar os setores de um hospital a um gerente de pessoas**

Critérios de aceitação:
- Gerar uma lista com todos os setores de um hospital;
- exigir token de login;
- verificar se é um supervisor ou um gerente de pessoas;
- testes.

**Comment by gag2502** [comment]
@gabibguedes @vitorl-s me procurem caso haja dificuldades :grinning:

**Comment by gabibguedes** [comment]
@egewarth @gag2502 , percebemos que para conseguirmos fazer a lista de setores precisamos primeiro criar setores, o que constitui um setor? Nome e gestor?

**Comment by gabibguedes** [comment]
@gag2502 que porta devemos usar para os setores?

**Comment by egewarth** [comment]
exato, está ligado na issue mas n precisa do criar em si.
Um setor pertence a um hospital, e contem um nome apenas. Os demais usuários estaram ligados a esse setor

**Comment by vitorl-s** [comment]
@eliseuegewarth pode me ajudar a resolver o problema de versão com o docker?  Ele não ta me permitindo rodar o docker, fala q a versão não é válida

**Comment by eliseuegewarth** [comment]
@vitorl-s desinstale totalmente o docker da sua máquina (`sudo apt purge <docker_package>` deve resolver). 
Após a desinstalação, execute esses comandos:
```bash
	echo "Adicionando chave pública Docker CE ..." && \
	sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D > /dev/null && \
	echo "Adicionando repositório Docker CE ..." && \
	sudo apt-add-repository 'deb https://apt.dockerproject.org/repo ubuntu-xenial main' > /dev/null && \
	echo "apt update ..." && \
	sudo apt-get -qq update > /dev/null && \
	echo "Checando repositório Docker CE ..." && \
	sudo apt-cache policy docker-engine > /dev/null && \
	echo "apt install ..." && \
	sudo apt-get -qq -y install nodejs build-essential google-chrome-stable sublime-text atom terminator docker-engine python-pip python3-pip htop > /dev/null && \
	echo "Baixando docker-compose ..." && \
	sudo curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose > /dev/null && \
	echo "Adicionando permissões para docker-compose ..." && \
	sudo chmod +x /usr/local/bin/docker-compose
	
```

**Comment by vitorl-s** [comment]
@eliseuegewarth deu certo! obrigado!
