### ISSUE TITLE
Criar horário de plantão (plantonista)

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/2018.1-Dulce_API#30]
Eu, como gestor, desejo criar um horário de escala de um plantonista, a fim de, organizar os horarios dos plantonistas

Critérios de aceitação:
- [x] Atributos:
  - Data
  - Horário inicio
  - Horário fim
  - Setor
  - Plantonista relacionado
  - Especialidade
  - Quantidade de horas (a partir do inicio-fim)

- [x] Validações:
  - Horário inicio não pode ser depois do fim
  - Horário de fim não pode ser antes do inicio
  - Setor é obrigatório
  - Plantonista é obrigatório
  - Verificar conflito de horários do plantonista

**1ø Code Review**  02/05 ás 21h
**2ø Code Review**  04/05 ás 23h

**Comment by gabibguedes** [comment]
Já foi feito a criação de escalas com os atributos selecionados, e as validações para os campos de horário de inicio, horário final, setor e plantonista também já estão implementadas.
Ainda falta a validação de conflitos de horário do plantonista e fazer a soma do total de horas pela api

**Comment by gag2502** [comment]
@gabibguedes Beleza 👍 parabéns Gabi

**Comment by gabibguedes** [comment]
Gente, como eu devo fazer a validação de caso a escala já exista? Tem que fazer uma busca no banco por todas as escalas do médico e verificar uma a uma se elas entram em conflito com a escala a ser criada? Como que faz essa consulta no banco?

**Comment by egewarth** [comment]
@gabibguedes Gabi, no caso você precisaria buscar inicialmente pelo dia, caso não retornasse nada não teria como haver conflito. Porém como faz essa consulta eu não estou a par, @gag12 sabr

**Comment by eliseuegewarth** [comment]
@gabibguedes Um bom ponto inicial é filtrar pela data do horário de serviço. Mas a verificação de colisão de horários é um pouco mais completa.
- Verificar se o horário de *início* está entre o horário inicio e o horário fim de algum plantão do mesmo dia
- Verificar se o horário de *fim* está entre o horário inicio e o horário fim de algum plantão do mesmo dia

**Comment by egewarth** [comment]
@eliseuegewarth Boa solução

**Comment by egewarth** [comment]
@gabibguedes João Egewarth:
Gabi, no caso você precisaria buscar inicialmente pelo dia, caso não retornasse nada não teria como haver conflito. Porém como faz essa consulta eu não estou a par, @gag2502 sabr

**Comment by gabibguedes** [comment]
Obrigada João

**Comment by gabibguedes** [comment]
@gag2502 Você pode me ajudar para fazer a consulta no banco?
