### ISSUE TITLE
Visualizar escala (plantonista)

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/2018.1-Dulce_API#37]
Eu, como plantonista, desejo visualizar minha escala a fim de saber meus horários de plantão

Critérios de aceitação:
- Usuário só pode visualizar caso esteja autenticado (login + token)
- Ver horário que está alocado no dia
- Ver dias que está alocado no mês
  - Ver dias que está alocado na semana (filtrar por semana)
- Ver horas de plantão na semana

**1ø Code Review**  02/05 ás 21h
**2ø Code Review**  04/05 ás 23h

**Comment by egewarth** [comment]
@fga-gpp-mds/eps-agr validem por favor

**Comment by egewarth** [comment]
@fga-gpp-mds/eps-agr , preciso do feedback de vocês, é importante pra diminuir os erros nas issues (como já rolou antes)

**Comment by BeatrizHanae** [comment]
Se for dividir 
Token -> estimate 2
Criar -> estimate 3

**Comment by EzequielDeOliveira** [comment]
@egewarth os horarios a serem visualizados sao os do usuario em questao ? por exemplo se eu for um medico vou ver so as minhas coisas ?

**Comment by egewarth** [comment]
@EzequielDeOliveira Tem 2 issues, a issue de visualização da escala do setor está com o Deusdará e o Fepas se não me engano.
A de vocês, se não me engano, é a de visualizar a própria apenas, mas verifique nas issues, a sua e a dele

**Comment by EzequielDeOliveira** [comment]
@egewarth Então mano , quero saber se a resposta que a API vai dar e pra um médico ou uma resposta completa , por exemplo quero ver as datas por mês , mostro de todos no banco

**Comment by EzequielDeOliveira** [comment]
@EzequielDeOliveira Ou mostro do o do médico que tá fazendo a requisição ?

**Comment by egewarth** [comment]
@EzequielDeOliveira Vou olhar tua issue pra n dar resposta errada

**Comment by EzequielDeOliveira** [comment]
@egewarth Tudo bem

**Comment by egewarth** [comment]
@EzequielDeOliveira A Issue fala na primeira linha...
"Eu, como PLANTONISTA, desejo visualizar MINHA escala, a fim de saber meus horários de plantão"

**Comment by EzequielDeOliveira** [comment]
@egewarth Certo então vou fazer tudo especifico , beijos

**Comment by EzequielDeOliveira** [comment]
@egewarth Obrigado

**Comment by egewarth** [comment]
@EzequielDeOliveira Por nada queridinho
