### ISSUE TITLE
Visualizar escala setor

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/2018.1-Dulce_API#38]
Eu, como plantonista, desejo visualizar escala do setor a fim de saber os horários de outros plantonistas

Critérios de aceitação:
- Visualizar horários dos médicos do mesmo setor
  - Ver horário que está alocado no dia
  - Ver dias que está alocado no mês
    - Ver dias que está alocado na semana (filtrar por semana)

**1ø Code Review**  02/05 ás 21h
**2ø Code Review**  04/05 ás 23h

**Comment by egewarth** [comment]
@fga-gpp-mds/eps-agr validem por favor, preciso desse feedback pra não errar nas issues dnv

**Comment by egewarth** [comment]
essa issue não foi planejada para essa sprint

**Comment by EzequielDeOliveira** [comment]
@egewarth Oque fazer então ?

**Comment by egewarth** [comment]
@EzequielDeOliveira Desculpa Ezequiel, eu li errado e me confundi, é para essa semana sim

**Comment by EzequielDeOliveira** [comment]
@egewarth Não desculpo

**Comment by fepas** [comment]
Essa Issue não é dependente da de criar?

**Comment by egewarth** [comment]
não

**Comment by egewarth** [comment]
@EzequielDeOliveira , essa issue que visualiza por setor.

**Comment by EzequielDeOliveira** [comment]
@egewarth Okey
