### ISSUE TITLE
Adequar projeto às diretrizes da comunidade GitHub

### ISSUE THREAD

**Issue by eliseuegewarth** [fga-gpp-mds/2018.1-Dulce_API#42]
### Nesta issue deve ser feito:
- Adequar o projeto aos [padrões da comunidade do GitHub](https://github.com/fga-gpp-mds/2018.1-Dulce_API/community)
- Analisar a necessidade de criar tudo novamente. O projeto do [aplicativo](https://github.com/fga-gpp-mds/2018.1-Dulce_App) já está adequado às mesmas diretrizes.

#### Critérios de Aceitação desta issue:
- [ ] Descrição do projeto
- [ ] Criação ou aprimoramento do [README](https://github.com/fga-gpp-mds/2018.1-Dulce_API/blob/master/README.md)
- [ ] Criação do Código de Conduta
- [ ] Criação do Guia de Contribuição
- [ ] Criação da Licença de distribuição do código
- [ ] Criação do Template para de Issues
- [ ] Criação do Template para de Pull Requests

**Comment by eliseuegewarth** [comment]
@alvesisaque Devo fazer esses passos no repositório da API ou nos repositórios dos microserviços (já modularizados)?

**Comment by alvesisaque** [comment]
@eliseuegewarth Acredito que seja nos microsserviços modularizados

**Comment by eliseuegewarth** [comment]
@alvesisaque Ok. Vou providenciar isso ainda hoje.
