### ISSUE TITLE
Criar escala

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/2018.1-Dulce_API#47]
Eu, como gestor, desejo criar uma escala de um plantonista, a fim de, organizar os horarios dos plantonistas de acordo com a regras definidas

Critérios de aceitação:
- [ ] Uma escala deve conter no máximo n dias. Sendo n a quantidade de dias do mês.
- [x] Uma escala deve conter no máximo n horários. Sendo n a quantidade de dias da escala.
- [x] Uma escala deve conter uma quantidade minima de horas por escala.
- [x] Uma escala deve conter uma quantidade minima de horas por semana.
- [ ] Uma escala deve pertencer a apenas um plantonista.
- [x] Um plantonista deve possuir uma escala por mês.
- [x] Uma escala deve conter as horas totais cumpridas (função, retorna o somatório de horas trabalhadas)

Atributos:
- [ ] Lista de Horários
- [x] Quantidade minima de horas por mês
- [x] Quantidade máxima de horas por mês
- [x] Quantidade minima de horas por semana
- [x] Quantidade máxima de horas por semana
- [x] Plantonista relacionado (FK)

**Comment by egewarth** [comment]
@gabibguedes e @vitorl-s , arrumem a issue de vocês, adicionem as labels e arrumem o pipeline dela

**Comment by vitorl-s** [comment]
@egewarth Ainda não começamos essa issue, mas ja coloquei as labels

**Comment by gabibguedes** [comment]
@egewarth, Na hora que o gestor for criar a escala do mês de um médico ele vai criar horário por horário pelo "criar horário" e o "criar escala" vai apenas filtrar o que já foi criado e adicionar as variáveis de horas por semana e mes ou ele vai criar todos os horários de uma vez em "criar escala"?

**Comment by egewarth** [comment]
@gabibguedes O criar escala é a criação do objeto escala que vai conter os objetos horários.
A escala é uma lista dos horários e os outros atributos, a gente precisa dela principalmente pelas validações que são importantes e não podem ser feitas nos horários

**Comment by egewarth** [comment]
@vitorl-s Esse é um atributo que, futuramente, vai ser cadastrado pelo gestor da instituição pois pode variar de instituição pra instituição e as vezes de setor pra setor

**Comment by gabibguedes** [comment]
E como que vamos validar? Se só vai ser implementado futuramente? ou a gente coloca como atributo da escala?

**Comment by egewarth** [comment]
@gabibguedes A validação é feita contando a quantidade de horas de um médico em um mês e/ou semana. Caso a quantidade seja maior que o valor cadastrado não pode deixar criar.

**Comment by egewarth** [comment]
@gabibguedes Houve um erro de interpretação ai na vdd
