### ISSUE TITLE
Escrever testes Unitarios para o serviço de Users

### ISSUE THREAD

**Issue by eliseuegewarth** [fga-gpp-mds/2018.1-Dulce_API#58]
Nessa issue será realizado:
- Reescrever testes do serviço user
- Desabilitar testes de integração

**Comment by alvesisaque** [comment]
http://senecajs.org/docs/tutorials/unit-testing.html

**Comment by alvesisaque** [comment]
Finalizada corretamente com com sucesso, um teste lindo no repositório do microserviços User. https://github.com/Dulce-Work-Schedule/2018.1-Dulce_User
